services:
  backend:
    container_name: medbrief_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend_data:/app_data
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - medbrief_network

  frontend:
    container_name: medbrief_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - backend
    networks:
      - medbrief_network

networks:
  medbrief_network:
    driver: bridge
